### ISSUE TITLE
Checklist Preparation

### ISSUE THREAD

**Issue by parismiguel** [IT-ORVAL/SalezPomeloTest1#1]
- [ ] Revisar competencia: Amazon Alexa, etc
- [ ] Configurar el DNS para utilizar una dirección URL amigable
- [ ] Hacer la carga del proyecto de forma persistente (ahora esta manual)
- [ ] Configurar para realizar actualizaciones desde otras máquinas (Publicacion continua de Visual Studio a CentOS)
- [ ] Habilitar el protocolo SSL
- [ ] Refactorizacion del Chat node.js
- [ ] Configurar proyecto en GitHub: definir equipo de trabajo, issues y milestones
- [ ] Documentar configuracion Core, Ngnix y Apache
- [ ] Instalar el CORE en el App Server
- [ ] Mover el proyecto Core Net con el Node.js
- [ ] Prueba Webhook SSL con Facebook
- [ ] Balance de carga
- [ ] Staging Development y Production MYSQL y WebServer
- [ ] BackUps MySQL
